import { createRequire } from "node:module";
import assert from "node:assert/strict";
import { writeFile } from "node:fs/promises";

const require = createRequire(import.meta.url);
const { chromium } = require(process.argv[2] || "playwright");
const url = process.env.DEMO_URL;
const password = process.env.DEMO_ACCESS_PASSWORD;
assert.ok(url && password, "Set DEMO_URL and DEMO_ACCESS_PASSWORD");
const anonymous = await fetch(url);
assert.equal(anonymous.status, 401, "public service must reject anonymous requests");
const browser = await chromium.launch({ channel: "msedge", headless: true });
const record = { executedAt: new Date().toISOString(), url, anonymousStatus: anonymous.status, data: "Live authorized iFinD; no raw provider response is written to this record" };
try {
  const page = await browser.newPage({ httpCredentials: { username: process.env.DEMO_ACCESS_USER || "demo", password } });
  const errors = [];
  page.on("pageerror", (e) => errors.push(e.message));
  await page.goto(url, { timeout: 60000 });
  await page.waitForFunction(() => !document.querySelector("#poolMeta").textContent.includes("读取"), { timeout: 90000 });
  record.poolDisclosure = await page.locator("#poolMeta").innerText();
  await page.waitForTimeout(5100);
  await page.locator("#intent").fill("TTM市盈率小于25，不要增加其他条件。");
  const parseResponse = page.waitForResponse((r) => new URL(r.url()).pathname === "/api/parse", { timeout: 180000 });
  await page.locator("#parseBtn").click();
  const parsedResponse = await parseResponse;
  assert.equal(parsedResponse.status(), 200);
  const parsed = await parsedResponse.json();
  assert.equal(parsed.aiStatus.used, true, "must actually use AI, not fallback rules");
  record.aiUsed = parsed.aiStatus.used;
  record.conditions = parsed.conditions.map((c) => ({ metric_id: c.metric_id, op: c.op, value: c.value, value_origin: c.value_origin }));
  assert.ok(parsed.conditions.some((c) => c.field === "peTtm" && c.value === 25));
  await page.waitForTimeout(5100);
  const screenResponse = page.waitForResponse((r) => new URL(r.url()).pathname === "/api/screen", { timeout: 180000 });
  await page.locator("#runBtn").click();
  const screenedResponse = await screenResponse;
  assert.equal(screenedResponse.status(), 200);
  const screened = await screenedResponse.json();
  record.screen = { poolSize: screened.poolSize, selected: screened.selected.length, excluded: screened.excluded.length, unknown: screened.unknown.length };
  const stocks = [...screened.selected, ...screened.excluded, ...screened.unknown];
  assert.equal(stocks.length, screened.poolSize);
  assert.ok(stocks.some((s) => s.explanation.checks.some((c) => c.actual !== null && c.actual !== undefined)), "at least one actual provider value is required");
  record.hasActualValues = true;
  record.hasQuoteTime = stocks.some((s) => !!s.quoteTime);
  const tab = screened.selected.length ? "selected" : screened.excluded.length ? "excluded" : "unknown";
  await page.locator(`[data-tab="${tab}"]`).click();
  await page.locator(".pick").first().check();
  await page.locator("#compareBtn").click();
  assert.equal(await page.locator("#compare tbody tr").count(), 1);
  await page.locator("#saveBtn").click();
  await page.waitForFunction(() => document.querySelector("#saveStatus").textContent.includes("保存成功"));
  await page.locator("#saved button").first().click();
  await page.waitForFunction(() => document.querySelector("#requestStatus").textContent.includes("已恢复"));
  assert.equal(await page.locator("#conditions input").first().inputValue(), "25");
  assert.match(await page.locator("#results").innerText(), /尚未执行/);
  assert.deepEqual(errors, []);
  record.compareSaveRestore = "passed";
  await writeFile("tmp/public-demo-validation.json", JSON.stringify(record, null, 2));
  console.log(JSON.stringify(record, null, 2));
} finally { await browser.close(); }
