export const METRIC_REGISTRY = [
  metric("revenueGrowth", "营收同比增长", "financial", "%", "最新一期营业收入相对上年同期变化率", "iFinD", "get_stock_financials: 营业收入(同比增长率)", "executable", ["营收增长", "收入增长", "销售增长"]),
  metric("profitGrowth", "净利润同比增长", "financial", "%", "最新一期净利润相对上年同期变化率", "iFinD", "get_stock_financials: 净利润(同比增长率)", "executable", ["利润增长", "净利润增长", "盈利改善"]),
  metric("operatingCashflowYoy", "经营现金流同比增长", "financial", "%", "经营活动现金流量净额相对上年同期变化率", "iFinD", "get_stock_financials: 经营活动产生的现金流量净额(同比增长率)", "executable", ["现金流改善", "经营现金流", "现金流增长"]),
  metric("revenueQoq", "营收环比增长", "financial", "%", "本期营业收入相对上一期变化率", "iFinD/Fuyao + deterministic", "营业收入本期/上一期", "unverified", ["营收环比", "收入环比"]),
  metric("profitQoq", "净利润环比增长", "financial", "%", "本期净利润相对上一期变化率", "iFinD/Fuyao + deterministic", "净利润本期/上一期", "unverified", ["利润环比", "净利环比"]),
  metric("epsYoy", "每股收益同比增长", "financial", "%", "每股收益相对上年同期变化率", "iFinD", "get_stock_financials: 基本每股收益(同比增长率)", "executable", ["EPS增长", "每股收益增长"]),
  metric("peTtm", "TTM 市盈率", "valuation", "x", "总市值 / 过去十二个月净利润", "iFinD", "stock_highfreq_quotes/get_stock_performance: 市盈率TTM", "executable", ["PE", "市盈率", "估值"]),
  metric("pb", "市净率", "valuation", "x", "总市值 / 归母净资产", "iFinD", "stock_highfreq_quotes: 市净率", "executable", ["PB", "市净率", "低估"]),
  metric("psTtm", "TTM 市销率", "valuation", "x", "总市值 / 过去十二个月营业收入", "iFinD/Fuyao", "市销率字段待核对", "unverified", ["PS", "市销率"]),
  metric("pcfTtm", "TTM 市现率", "valuation", "x", "总市值 / 过去十二个月经营现金流", "iFinD/Fuyao", "市现率字段待核对", "unverified", ["PCF", "市现率"]),
  metric("peIndustryRank", "行业 PE 分位", "valuation", "%", "个股 PE 在所属行业内的从低到高分位", "iFinD/Fuyao + deterministic", "行业成分 + PE 排名", "missing", ["同行便宜", "行业低估", "行业分位"]),
  metric("peHistoryPercentile", "历史 PE 分位", "valuation", "%", "当前 PE 位于个股历史 PE 序列的分位", "iFinD/Fuyao + deterministic", "历史 PE 序列", "missing", ["历史低位", "估值历史分位"]),
  metric("marketCapBillion", "总市值", "universe", "亿元", "股票总市值，按亿元归一", "iFinD", "stock_highfreq_quotes: 总市值 / 1e8", "executable", ["市值", "大市值", "小盘"]),
  metric("listingAgeDays", "上市天数", "universe", "天", "股票上市以来经过的自然日数量", "iFinD/Fuyao", "上市日期字段待核对", "unverified", ["新股", "次新股", "上市时间"]),
  metric("industryName", "所属行业", "universe", "", "个股所属行业分类", "iFinD/Fuyao", "个股行业映射字段待核对", "missing", ["行业", "板块", "赛道"]),
  metric("latestPrice", "最新价", "quote", "元", "最新成交价格", "iFinD", "stock_highfreq_quotes: 最新价", "executable", ["股价", "价格", "最新价"]),
  metric("intradayChangePct", "当日涨跌幅", "quote", "%", "当日最新涨跌幅", "iFinD", "stock_highfreq_quotes: 涨跌幅", "executable", ["涨幅", "当日涨幅", "涨跌幅"]),
  metric("openGapPct", "开盘缺口", "quote", "%", "开盘价相对上一收盘价的涨跌幅", "iFinD/Fuyao + deterministic", "开盘价/昨收价", "unverified", ["高开", "低开", "缺口"]),
  metric("closeNearHighPct", "收盘接近最高价", "quote", "%", "收盘价距离当日最高价的比例", "iFinD/Fuyao + deterministic", "最高价/收盘价", "unverified", ["收在高位", "尾盘收强"]),
  metric("volume", "成交量", "volume", "股", "当日成交量", "iFinD", "stock_highfreq_quotes: 成交量", "executable", ["成交量", "放量", "缩量"]),
  metric("volumeRatio", "量比", "volume", "", "当前成交强度相对近期平均成交强度的比例", "iFinD", "stock_highfreq_quotes: 量比", "executable", ["量比", "成交活跃"]),
  metric("volumeToAvg5", "成交量/5日均量", "volume", "倍", "当日成交量除以最近 5 日平均成交量", "iFinD", "get_stock_performance: 成交量 / N日日均成交量", "executable", ["5日均量", "放量"]),
  metric("volumeToAvg20", "成交量/20日均量", "volume", "倍", "当日成交量除以最近 20 日平均成交量", "iFinD/Fuyao + deterministic", "成交量 / 20日日均成交量", "unverified", ["20日均量", "持续放量"]),
  metric("turnoverRate", "换手率", "volume", "%", "成交股数占流通股本比例", "iFinD", "stock_highfreq_quotes: 换手率", "executable", ["换手率", "筹码活跃"]),
  metric("amountBillion", "成交额", "liquidity", "亿元", "当日成交金额，按亿元归一", "iFinD", "stock_highfreq_quotes: 成交额 / 1e8", "executable", ["成交额", "流动性"]),
  metric("amountRank", "成交额排名", "liquidity", "名", "股票池内按当日成交额从高到低排名", "iFinD + deterministic", "成交额排序", "unverified", ["成交额排名", "人气排名"]),
  metric("priceAboveMa5", "价格高于5日均线", "trend", "", "最新价是否高于 5 日简单移动平均线", "iFinD + deterministic", "最新价 > MA5", "executable", ["5日线", "五日线", "站上5日线"]),
  metric("priceAboveMa10", "价格高于10日均线", "trend", "", "最新价是否高于 10 日简单移动平均线", "iFinD + deterministic", "最新价 > MA10", "executable", ["10日线", "十日线", "跌破十日线"]),
  metric("amplitude60d", "近 60 日振幅", "trend", "%", "近 60 日区间振幅", "iFinD", "get_stock_performance: 区间振幅", "executable", ["振幅", "波动", "走势稳定"]),
  metric("return60d", "近 60 日涨跌幅", "trend", "%", "近 60 日累计涨跌幅", "iFinD", "get_stock_performance: N日涨跌幅", "executable", ["回撤", "下跌", "走势"]),
  metric("relativeStrength60d", "近 60 日相对强弱", "trend", "分", "近 60 日涨跌幅在股票池或市场中的相对排名得分", "iFinD/Fuyao + deterministic", "涨跌幅横截面排名", "unverified", ["相对强弱", "RS排名", "强于大盘"]),
  metric("newHigh60d", "创 60 日新高", "trend", "", "最新价是否达到近 60 日最高价", "iFinD/Fuyao + deterministic", "最新价 >= 60日最高价", "unverified", ["新高", "突破前高", "突破平台"]),
  metric("notSpecialTreatment", "非 ST/退市预警", "risk", "", "证券简称不含 ST、*ST、退等风险标记", "local deterministic", "name regex", "executable", ["ST", "退市", "风险"]),

  metric("ma5TrendUp", "5日均线向上", "trend", "", "MA5 较上一交易日抬升", "iFinD", "需要历史 MA5 对比", "unverified", ["5日线往上", "五日均线向上"]),
  metric("ma10TrendUp", "10日均线向上", "trend", "", "MA10 较上一交易日抬升", "iFinD", "需要历史 MA10 对比", "unverified", ["10日线往上", "十日均线向上"]),
  metric("priceAboveMa20", "价格高于20日均线", "trend", "", "最新价是否高于 20 日均线", "iFinD + deterministic", "stock_highfreq_quotes 最新价 + get_stock_performance: 最新20日均线", "executable", ["20日线", "二十日线"]),
  metric("maBullishAlignment", "均线多头排列", "trend", "", "MA5 > MA10 > MA20", "iFinD + deterministic", "get_stock_performance: MA5/MA10/MA20 组合", "executable", ["多头排列", "均线多头"]),
  metric("ema20TrendUp", "EMA20 向上", "trend", "", "20 日指数移动平均线较上一交易日抬升", "iFinD/Fuyao + deterministic", "EMA20 今日/昨日", "unverified", ["EMA20", "指数均线"]),
  metric("bollBreakUpper", "突破布林上轨", "technical", "", "最新价是否上穿布林线上轨", "iFinD/Fuyao + deterministic", "BOLL 上轨", "unverified", ["布林线", "BOLL", "突破上轨"]),
  metric("bollWidthPercentile252", "布林带宽度 252 日分位", "setup", "%", "当前布林带宽度在近 252 日中的分位，低分位代表挤压", "StockScreener contract + deterministic", "se_bb_width_pctile_252", "missing", ["布林收口", "BB squeeze", "波动收缩"]),
  metric("atr14", "ATR(14)", "technical", "%", "14 周期平均真实波幅，按价格百分比归一", "iFinD/Fuyao + deterministic", "最高/最低/收盘历史序列", "unverified", ["ATR", "真实波幅", "波动率"]),
  metric("rsi6", "RSI(6)", "technical", "", "6 周期相对强弱指标", "iFinD", "get_stock_performance: RSI相对强弱指标 周期6", "executable", ["RSI", "超买", "超卖"]),
  metric("stochRsiK", "STOCHRSI K值", "technical", "", "随机 RSI 的 K 值", "InStock indicator_web_dic.py", "stochrsi_k", "missing", ["随机RSI", "STOCHRSI"]),
  metric("williamsR14", "威廉指标 WR(14)", "technical", "", "14 周期 Williams %R，常用 -20/-80 判断超买超卖", "StockAnalyzer signals.py + InStock indicator_web_dic.py", "wr_14 / WILLIAMS_*", "unverified", ["威廉指标", "WR", "W&R"]),
  metric("cci20", "CCI(20)", "technical", "", "20 周期顺势指标，常用 +100/-100 判断强弱", "StockAnalyzer signals.py + InStock indicator_web_dic.py", "cci / CCI_*", "unverified", ["CCI", "顺势指标"]),
  metric("adx14", "ADX(14)", "technical", "", "平均趋向指标，用于判断趋势强度", "InStock indicator_web_dic.py", "adx", "missing", ["ADX", "趋势强度", "DMI"]),
  metric("macdDiff", "MACD DIFF", "technical", "", "MACD 快线 DIF", "iFinD", "get_stock_performance: MACD指标选项 DIFF", "executable", ["MACD", "金叉", "死叉"]),
  metric("macdGoldenCross", "MACD 金叉", "technical", "", "MACD DIFF 上穿 DEA", "iFinD/Fuyao + deterministic", "MACD DIFF/DEA 历史对比", "unverified", ["MACD金叉", "金叉"]),
  metric("kdjK", "KDJ K值", "technical", "", "KDJ 随机指标 K 值", "iFinD", "get_stock_performance: KDJ随机指标 K值", "executable", ["KDJ", "随机指标"]),
  metric("obvTrendUp", "OBV 向上", "technical", "", "能量潮 OBV 近期趋势向上", "iFinD/Fuyao + deterministic", "成交量与涨跌方向序列", "unverified", ["OBV", "能量潮"]),
  metric("mfi14", "MFI(14)", "technical", "", "资金流量指标，结合价格和成交量衡量资金强弱", "InStock indicator_web_dic.py", "mfi / mfisma", "missing", ["MFI", "资金流量"]),
  metric("vwmaDistance", "价格偏离 VWMA", "technical", "%", "价格相对成交量加权均线的偏离幅度", "InStock indicator_web_dic.py + deterministic", "close / vwma - 1", "missing", ["VWMA", "量价均线"]),
  metric("supertrendBullish", "SuperTrend 多头", "technical", "", "价格处于 SuperTrend 多头状态", "InStock indicator_web_dic.py", "supertrend", "missing", ["超级趋势", "SuperTrend"]),
  metric("ppoDiff", "PPO 差值", "technical", "", "价格震荡百分比指标 PPO 快慢线差", "InStock indicator_web_dic.py", "ppo / ppos / ppoh", "missing", ["PPO", "价格震荡"]),
  metric("sarBullish", "SAR 多头", "technical", "", "价格位于 SAR 上方或 SAR 处于多头方向", "InStock indicator_web_dic.py", "sar", "missing", ["SAR", "抛物线"]),
  metric("forceIndex13", "劲道指数 FI(13)", "technical", "", "价格变化与成交量结合的 Force Index", "InStock indicator_web_dic.py", "force_13", "missing", ["FI", "劲道指数"]),
  metric("minerviniScore", "Minervini 评分", "setup", "分", "趋势模板综合评分，常用于筛选二阶段强势股", "StockScreener scan_filter_fields.json", "minervini_score", "missing", ["米勒维尼", "Minervini", "趋势模板"]),
  metric("canslimScore", "CANSLIM 评分", "setup", "分", "CANSLIM 基本面与技术面综合评分", "StockScreener scan_filter_fields.json", "canslim_score", "missing", ["CANSLIM", "欧奈尔"]),
  metric("compositeScore", "综合评分", "setup", "分", "多策略合成评分", "StockScreener scan_filter_fields.json", "composite_score", "missing", ["综合评分", "Composite score"]),
  metric("vcpDetected", "VCP 形态识别", "setup", "", "波动收缩形态是否出现", "StockScreener scan_filter_fields.json", "vcp_detected", "missing", ["VCP", "波动收缩形态"]),
  metric("vcpReady", "VCP 接近突破", "setup", "", "VCP 形态是否进入接近突破状态", "StockScreener scan_filter_fields.json", "vcp_ready_for_breakout", "missing", ["VCP突破", "接近突破"]),
  metric("pocketPivot", "Pocket Pivot", "setup", "", "相对近期下跌日成交量的口袋支点信号", "StockScreener scan_filter_fields.json", "pocket_pivot", "missing", ["口袋支点", "Pocket Pivot"]),
  metric("powerTrend", "Power Trend", "setup", "", "强趋势状态标记", "StockScreener scan_filter_fields.json", "power_trend", "missing", ["Power Trend", "强趋势"]),
  metric("distanceToPivotPct", "距离枢轴点", "setup", "%", "当前价距离突破枢轴价的百分比", "StockScreener scan_filter_fields.json", "se_distance_to_pivot_pct", "missing", ["枢轴点", "pivot", "买点距离"]),
  metric("baseDepthPct", "底部形态深度", "setup", "%", "整理形态从高点到低点的回撤深度", "StockScreener scan_filter_fields.json", "se_base_depth_pct", "missing", ["base depth", "形态深度", "整理深度"]),
  metric("upDownVolumeRatio10d", "10日涨跌量比", "volume", "倍", "近 10 日上涨日成交量相对下跌日成交量的比例", "StockScreener scan_filter_fields.json", "se_up_down_volume_ratio_10d", "missing", ["涨跌量比", "up down volume"]),
  metric("rsLineNewHigh", "RS 线新高", "setup", "", "相对强弱线是否创新高", "StockScreener scan_filter_fields.json", "rs_line_new_high", "missing", ["RS线新高", "相对强弱线"]),
  metric("rsLineBlueDotRecent", "RS 蓝点", "setup", "", "近期出现 RS 蓝点信号", "StockScreener scan_filter_fields.json", "rs_line_blue_dot_recent", "missing", ["蓝点", "RS Blue Dot"]),
  metric("roe", "ROE", "quality", "%", "净利润 / 净资产", "iFinD", "get_stock_financials: 净资产收益率ROE", "executable", ["ROE", "净资产收益率"]),
  metric("grossMargin", "毛利率", "quality", "%", "毛利 / 营业收入", "iFinD", "get_stock_financials: 销售毛利率", "executable", ["毛利率", "高毛利"]),
  metric("netMargin", "净利率", "quality", "%", "净利润 / 营业收入", "iFinD", "get_stock_financials: 销售净利率", "executable", ["净利率", "利润率"]),
  metric("roic", "ROIC", "quality", "%", "税后经营利润 / 投入资本", "iFinD/Fuyao", "财务指标接口待核对字段", "unverified", ["投入资本回报率", "资本回报"]),
  metric("debtAssetRatio", "资产负债率", "risk", "%", "总负债 / 总资产", "iFinD", "get_stock_financials: 资产负债率", "executable", ["负债率", "低负债"]),
  metric("currentRatio", "流动比率", "risk", "x", "流动资产 / 流动负债", "iFinD", "get_stock_financials: 流动比率", "executable", ["偿债能力", "流动比率"]),
  metric("dividendYield", "股息率", "income", "%", "每股股息 / 股价", "valuation/dividend", "待核对实际接口字段", "unverified", ["股息率", "分红", "红利"]),
  metric("mainNetInflow", "主力净流入", "money_flow", "万元", "主力资金净流入金额", "iFinD/Fuyao", "资金流字段待接入", "missing", ["主力", "大单", "资金流"]),
  metric("largeOrderNetInflow", "大单净流入", "money_flow", "万元", "大单成交买入金额减卖出金额", "iFinD/Fuyao", "大单资金流字段待接入", "missing", ["大单净流入", "大单买入"]),
  metric("northboundNetBuy", "北向资金净买入", "money_flow", "万元", "北向资金对个股的净买入金额", "iFinD/Fuyao", "陆股通持股/成交字段待接入", "missing", ["北向资金", "外资买入"]),
  metric("sectorRisingCount", "行业上涨家数", "sector", "家", "所属行业当日上涨成分股数量", "iFinD/Fuyao + deterministic", "板块成分 + 成分股涨跌幅", "missing", ["上涨家数", "板块共振"]),
  metric("sectorChangePct", "所属行业涨跌幅", "sector", "%", "个股所属行业当日涨跌幅", "iFinD/Fuyao", "个股行业映射 + 板块行情", "missing", ["板块涨幅", "行业涨幅"]),
  metric("sectorRisingRatio", "行业上涨比例", "sector", "%", "所属行业上涨家数 / 行业成分股数", "iFinD/Fuyao + deterministic", "板块成分 + 成分股行情", "missing", ["行业上涨比例", "板块普涨"]),
  metric("sectorRankByChange", "行业涨幅排名", "sector", "名", "所属行业在全部行业中的当日涨幅排名", "iFinD/Fuyao + deterministic", "行业指数涨跌幅排序", "missing", ["板块排名", "行业排名"]),
  metric("conceptHotnessRank", "概念热度排名", "sector", "名", "所属概念板块的热度排名", "iFinD/Fuyao", "概念热度字段待接入", "missing", ["热门概念", "题材热度"])
];

function metric(id, name, category, unit, definition, provider, field, availability, aliases = []) {
  return {
    id,
    name,
    aliases,
    category,
    definition,
    unit,
    parameters: {},
    source: { provider, field },
    operators: ["gt", "gte", "lt", "lte", "eq", "between"],
    availability,
    missing_policy: "unknown"
  };
}

export const METRIC_BY_ID = Object.fromEntries(METRIC_REGISTRY.map((item) => [item.id, item]));

export const FIELD_DEFS = Object.fromEntries(METRIC_REGISTRY.map((item) => [
  item.id,
  {
    label: item.name,
    unit: item.unit,
    source: `${item.source.provider}: ${item.source.field}`,
    help: item.definition,
    availability: item.availability
  }
]));
